#!/usr/bin/env python 

from bitcoinrpc.authproxy import AuthServiceProxy
from docker import Client
import time

dockercli = Client(base_url='unix://var/run/docker.sock',version='1.12')
rpc_user = 'user'
rpc_password = 'pass'

nsrport = ((dockercli.port('node1', 15001))[0]['HostPort'])
nbtport = ((dockercli.port('node1', 15002))[0]['HostPort'])

rpcnsr = AuthServiceProxy("http://" + rpc_user + ":" + rpc_password + "@127.0.0.1:" + nsrport)
rpcnbt = AuthServiceProxy("http://" + rpc_user + ":" + rpc_password + "@127.0.0.1:" + nbtport)

rpcnsrgui = AuthServiceProxy("http://" + rpc_user + ":" + rpc_password + "@127.0.0.1:15001")
rpcnbtgui = AuthServiceProxy("http://" + rpc_user + ":" + rpc_password + "@127.0.0.1:15002")

#while (rpcnbtgui.getinfo()['blocks']) != 400:
# print((rpcnbtgui.getinfo()['blocks']))
# time.sleep(10)
#print("done mining")

custadd = rpcnbt.getnewaddress()


