#!/bin/bash

#Install dependencies


#These are required to build the daemon. It also installs docker and python package manageer.
sudo apt-add-repository ppa:bitcoin/bitcoin -y

sudo apt-get update
sudo apt-get install git build-essential g++ libssl-dev libboost-all-dev libdb4.8++-dev libqrencode-dev qt4-qmake libqt4-dev docker.io libcurl4-openssl-dev python-pip -y

#Needed to install docker
sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
sudo sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io

#Install Mini-UPnPC
cd ~
mkdir miniupnpcInstall
cd miniupnpcInstall
wget "http://miniupnp.tuxfamily.org/files/download.php?file=miniupnpc-1.9.tar.gz"
tar -zxvf download.php?file=miniupnpc-1.9.tar.gz
cd miniupnpc-1.9/
sudo make install

cd ~
rm -rf ~/miniupnpc

#Upgrade python package manager then install bitcoinrpc and docker python libraries
sudo pip install --upgrade pip
sudo pip install python-bitcoinrpc docker-py simplejson

#Use docker without sudo
sudo groupadd docker
sudo gpasswd -a ${USER} docker
sudo service docker.io restart
newgrp docker
