#!/usr/bin/env python

import sys
import time
import random
from askrpc import *

while True:

 test = random.randint(1,2)
 test2 = random.randint(1,2)

#try:

 if test == 1:
  if test2 == 1:
   sendnbt("docker")
  if test2 == 2:
   sendnsr("docker")

 if test == 2:
  if test2 == 1:
   sendnbt("gui")
  if test2 == 2:
   sendnsr("gui")

 time.sleep(.2)

#except Exception:
# pass

if "gui" in sys.argv:
 print "were in the gui"

if "docker" in sys.argv:
 print "we're in the daemon"

